### ISSUE TITLE
write generated CSS files to target directory

### ISSUE THREAD

**Issue by M1cha** [abishekatp/stylers#11]
Having proc-macros or build script write anywhere outside of `target` doesn't seem like a good idea since it requires extra ignore rules and cleanup steps.

**Comment by abishekatp** [comment]
Yeah it seems what you are suggesting is good idea. I will try to move css directory and mani.css file to the target directory.

**Comment by abishekatp** [comment]
Fixed this issue here https://github.com/abishekatp/stylers/pull/12.
Thank you for suggesting this idea. Moving the main.css file to the target directory solved the multiple re-render issue. Also thank you for helping me out [for this issue](https://github.com/thedodd/trunk/issues/502) @thedodd and @adriaanjoubert. Closing this issue now.
