### ISSUE TITLE
css generated directory

### ISSUE THREAD

**Issue by luoxiaozero** [abishekatp/stylers#22]
I have an application that uses [melt-ui (leptos UI library)](https://github.com/luoxiaozero/melt-ui), and melt-ui uses stylers, but the css files generated by stylers are in the melt-ui directory. I tried to solve it, but it didn't work.

**Comment by luoxiaozero** [comment]
Is there any solution

**Comment by abishekatp** [comment]
Yeah there is a solution,
- First thing both `style!`  and `style_sheet!` macro generates css files that can be used to serve the css file separately from the server. 
- In contrast with above both `style_str!` and `style_sheet_str!` will return the style string instead of writing into separate css file.

For your use case: 
 In your use case you want to export the components to other users. so you can't export separate css file for each component. I think you can use either `style_str!` or `styel_sheet_str!`. you can find code snippet in [readme](https://github.com/abishekatp/stylers#stylers) or detailed example in [examples directory](https://github.com/abishekatp/stylers/tree/main/examples)

**Comment by luoxiaozero** [comment]
I know the solution
1. Repeated use of components results in multiple style
![{P_YX48$F~IKP}F1E`2II L](https://user-images.githubusercontent.com/48741584/228710279-9628a95a-4794-4f2e-9420-d60e0d52d50a.png)
2. style in the head. Create the component again to check if the head exists. There's going to be a runtime

It don't feel elegant

**Comment by abishekatp** [comment]
I am checking weather there is better way to do this. Please give me some time.

**Comment by luoxiaozero** [comment]
ok

**Comment by abishekatp** [comment]
Since this problem is solvable using the above discussed approach I am closing this issue now.
